# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAzs',
            fields=[
                ('road_code', models.IntegerField(blank=False, null=False)),
                ('geomtype', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_azs',
                'managed': True,
                # 'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRoads',
            fields=[
                ('road_code', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('length_km', models.TextField(blank=True, null=True)),
                ('geomtype', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_roads',
                # 'managed': False,
                'managed': True,
            },
        ),
    ]
