# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblazs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblroads',
            options={},
        ),
    ]
