# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20180219_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblAzs',
            new_name='Azs',
        ),
        migrations.RenameModel(
            old_name='TblRoads',
            new_name='Roads',
        ),
    ]
