# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_auto_20180219_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azs',
            name='road_code',
            field=models.ForeignKey(db_column='road_code', on_delete=django.db.models.deletion.CASCADE, related_query_name='azs', to='roads.Roads', to_field='road_code'),
        ),
        migrations.AlterField(
            model_name='roads',
            name='road_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
