# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_auto_20180219_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='road_code',
            field=models.IntegerField(unique=True),
        ),
    ]
